local wk = require "which-key"
--
-- wk.register {
--     { "<leader>a", group = "auto actions" },
--     { "<leader>f", group = "telescope actions" },
--     { "<leader>g", group = "git actions" },
--     { "<leader>gb", group = "git blame" },
--     { "<leader>j", group = "lsp jump" },
--     { "<leader>jf", group = "lsp telescope" },
--     { "<leader>l", group = "lsp config" },
--     { "<leader>s", group = "set syntax" },
--     { "<leader>t", group = "toggle" },
-- }
-- local a = {
--   -- add group
--   ["<leader>"] = {
--     g = { name = "git actions" },
--     j = { name = "lsp jump" },
--     l = { name = "lsp config" },
--     f = { name = "telescope actions" },
--     s = { name = "set syntax" },
--     t = { name = "toggle" },
--     a = { name = "auto actions" },
--   },
--   ["<leader>j"] = {
--     f = { name = "lsp telescope" },
--   },
--   ["<leader>g"] = {
--     b = { name = "git blame" },
--   },
-- }
